title: HRSE - Human Readable S-Expressions
repository: lukebemish/hrse
author: Luke Bemish
plugins:
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
description: >-
  HRSE is a config and data-serialization language offering a compromise bwtween the flexibility of a language such as JSON 
  and the human-readability of a config language such as TOML. HRSE is designed to be easy for a human to read or write, and
  sacrifices some ease of parsing for this purpose. Any HRSE document should have an equivalent representation as an
  s-expression, and in fact s-expressions should be valid members within a HRSE document.
remote_theme: jekyll/minima@2863624b903b17f838d6ce8d2f77900fa9d3c864
minima:
  skin: auto